export const presets = [
  {
    name: 'Jvke Blush (Sample)',
    id: 'jvke-blush',
    settings: {
      dotsOptions: { type: 'square', color: '#1E1B18' },
      cornersSquareOptions: { type: 'square', color: '#1E1B18' },
      cornersDotOptions: { type: 'square', color: '#1E1B18' },
      backgroundOptions: { color: 'transparent', transparent: true },
      cardOptions: {
        enabled: true,
        headerText: 'connect with us',
        headerFont: 'Dancing Script',
        subText: '@YourSocialHandle',
        footerText: 'www.YourSite.com',
        bgColor: '#FED0C5',
        textColor: '#1E1B18',
        cornerRadius: 80,
      },
    },
  },
  {
    name: 'Warm Cream',
    id: 'warm-cream',
    settings: {
      dotsOptions: { type: 'rounded', color: '#2B2118' },
      cornersSquareOptions: { type: 'extra-rounded', color: '#2B2118' },
      cornersDotOptions: { type: 'dot', color: '#2B2118' },
      backgroundOptions: { color: 'transparent', transparent: true },
      cardOptions: {
        enabled: true,
        headerText: 'connect with us',
        headerFont: 'Caveat',
        subText: '@yourhandle',
        footerText: 'hello@yoursite.com',
        bgColor: '#FDF0D5',
        textColor: '#2B2118',
        cornerRadius: 80,
      },
    },
  },
  {
    name: 'Sage Modern',
    id: 'sage-modern',
    settings: {
      dotsOptions: { type: 'classy', color: '#1B3B36' },
      cornersSquareOptions: { type: 'extra-rounded', color: '#1B3B36' },
      cornersDotOptions: { type: 'square', color: '#1B3B36' },
      backgroundOptions: { color: 'transparent', transparent: true },
      cardOptions: {
        enabled: true,
        headerText: 'scan to explore',
        headerFont: 'Dancing Script',
        subText: '@studio.design',
        footerText: 'www.studiodesign.io',
        bgColor: '#DCE7E1',
        textColor: '#1B3B36',
        cornerRadius: 80,
      },
    },
  },
  {
    name: 'Noir Luxe',
    id: 'noir-luxe',
    settings: {
      dotsOptions: { type: 'square', color: '#F4F4F6' },
      cornersSquareOptions: { type: 'square', color: '#F4F4F6' },
      cornersDotOptions: { type: 'square', color: '#F4F4F6' },
      backgroundOptions: { color: 'transparent', transparent: true },
      cardOptions: {
        enabled: true,
        headerText: 'connect with us',
        headerFont: 'Dancing Script',
        subText: '@brand.exclusive',
        footerText: 'vip.brand.com',
        bgColor: '#161618',
        textColor: '#F4F4F6',
        cornerRadius: 80,
      },
    },
  },
  {
    name: 'QR Only (Classic)',
    id: 'classic-qr',
    settings: {
      dotsOptions: { type: 'square', color: '#000000' },
      cornersSquareOptions: { type: 'square', color: '#000000' },
      cornersDotOptions: { type: 'square', color: '#000000' },
      backgroundOptions: { color: '#ffffff', transparent: false },
      cardOptions: {
        enabled: false,
        headerText: 'connect with us',
        headerFont: 'Dancing Script',
        subText: '@YourSocialHandle',
        footerText: 'www.YourSite.com',
        bgColor: '#FED0C5',
        textColor: '#1E1B18',
        cornerRadius: 80,
      },
    },
  },
];
